FROM python:3.12-alpine
WORKDIR /flask
RUN apk update && apk upgrade
RUN apk add --no-cache tzdata
ENV TZ=Europe/London
# See here for timezones:
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
COPY requirements requirements
RUN pip install --upgrade pip
RUN pip install -r requirements/production.txt

ENTRYPOINT ["sh"]
